//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ADR
    {
        public int Id { get; set; }
        public System.DateTime Date { get; set; }
        public int KidId { get; set; }
        public string AchievementsTeachers { get; set; }
        public string AchievementsParents { get; set; }
        public string DifficultiesTeachers { get; set; }
        public string DifficultiesParents { get; set; }
        public string RecommendationsTeachers { get; set; }
        public string RecommendationsParents { get; set; }
        public bool Performed { get; set; }
        public Nullable<System.DateTime> StartPeriod { get; set; }
        public Nullable<System.DateTime> EndPeriod { get; set; }
    
        public virtual Kid Kid { get; set; }
    }
}
