//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmotionObservation
    {
        public int Id { get; set; }
        public int KidId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public string Comment { get; set; }
        public System.DateTime DateObserved { get; set; }
        public Sadik.Models.EmotionType Emotion { get; set; }
        public System.Guid UniqueId { get; set; }
    
        public virtual Kid Kid { get; set; }
        public virtual User User { get; set; }
    }
}
