//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemUsageDetail
    {
        public System.Guid UniqueId { get; set; }
        public int KidId { get; set; }
        public int ItemId { get; set; }
        public Nullable<int> TeacherId { get; set; }
        public Nullable<System.DateTime> PresentationDate { get; set; }
        public Nullable<SkillDegree> Degree { get; set; }
    
        public virtual Inventory Inventory { get; set; }
        public virtual Kid Kid { get; set; }
        public virtual User User { get; set; }
    }
}
