//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TemplateZone
    {
        public TemplateZone()
        {
            this.TemplateInventories = new HashSet<TemplateInventory>();
            this.TemplateZones1 = new HashSet<TemplateZone>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentZoneId { get; set; }
    
        public virtual ICollection<TemplateInventory> TemplateInventories { get; set; }
        public virtual ICollection<TemplateZone> TemplateZones1 { get; set; }
        public virtual TemplateZone TemplateZone1 { get; set; }
    }
}
