//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Activities = new HashSet<Activity>();
            this.Presentations = new HashSet<Presentation>();
            this.CameInClasses = new HashSet<CameInClass>();
            this.EmotionObservations = new HashSet<EmotionObservation>();
            this.UserKindergartens = new HashSet<UserKindergarten>();
            this.ItemUsageDetails = new HashSet<ItemUsageDetail>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public byte[] PasswordHash { get; set; }
        public byte[] PasswordSalt { get; set; }
        public UserRole RoleId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<Activity> Activities { get; set; }
        public virtual ICollection<Presentation> Presentations { get; set; }
        public virtual ICollection<CameInClass> CameInClasses { get; set; }
        public virtual ICollection<EmotionObservation> EmotionObservations { get; set; }
        public virtual ICollection<UserKindergarten> UserKindergartens { get; set; }
        public virtual ICollection<ItemUsageDetail> ItemUsageDetails { get; set; }
    }
}
