//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKindergarten
    {
        public int Id { get; set; }
        public int UserId { get; set; }
        public int KindergartenId { get; set; }
        public UserRole RoleId { get; set; }
    
        public virtual Kindergarten Kindergarten { get; set; }
        public virtual User User { get; set; }
    }
}
