//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sadik.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zone
    {
        public Zone()
        {
            this.Inventories = new HashSet<Inventory>();
            this.ChildZones = new HashSet<Zone>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> ParentZoneId { get; set; }
        public int KindergartenId { get; set; }
    
        public virtual ICollection<Inventory> Inventories { get; set; }
        public virtual ICollection<Zone> ChildZones { get; set; }
        public virtual Zone ParentZone { get; set; }
        public virtual Kindergarten Kindergarten { get; set; }
    }
}
